import assert from 'node:assert/strict';
import { inferBusBranches } from '../packages/domain/busBranch.ts';
process.env.BLOOMCORE_DB = ':memory:';
process.env.DATABASE_URL = '';
process.env.REDIS_URL = '';
const { setCollection, getCollection } = await import('./datastore.ts');
const { applyWrite, deltaToWhole, GuardError } = await import('./guards.ts');
const { runBusBranchMigration } = await import('./migrateBusBranches.ts');
const { filterReadable, assertCanWrite } = await import('./rbac.ts');
const bus = (id: string, branch?: 'church' | 'light'): any => ({ id, name: id, commune: 'Cocody', zone: 'Centre', centerLat: 5.35, centerLng: -4, ...(branch ? { branch } : {}) });
const member = (id: string, branch: string, bloomBusId?: string): any => ({ id, branch, bloomBusId, departments: {}, level: 'stagiaire', pastoralCursus: 'aucun' });
const original = [bus('single'), bus('mixed'), bus('empty'), bus('declared', 'church'), bus('invalid')];
const people = [member('a', 'light', 'single'), member('b', 'church', 'mixed'), member('c', 'light', 'mixed'),
  member('d', 'light', 'declared'), member('e', 'global', 'invalid')];
const inferred = inferBusBranches(original, people);
assert.deepEqual(inferred.migratedIds, ['single']);
assert.deepEqual(inferred.unresolvedIds, ['mixed', 'empty', 'declared', 'invalid']);
assert.equal(original[0].branch, undefined, 'migration pure, entrée inchangée');
assert.equal(inferred.buses[0].branch, 'light');
assert.equal(inferred.buses[3].branch, 'church', 'ne remplace pas une branche déclarée');
assert.deepEqual(inferBusBranches(inferred.buses, people).migratedIds, []);
await setCollection('members', people);
await setCollection('bus_lines', original);
await runBusBranchMigration();
const once = await getCollection('bus_lines');
await runBusBranchMigration();
assert.deepEqual(await getCollection('bus_lines'), once, 'redémarrage idempotent');
assert.deepEqual(await getCollection('members'), people, 'aucun membre déplacé');

await setCollection('members', []);
await setCollection('bus_lines', [bus('church_bus', 'church'), bus('light_bus', 'light'), bus('legacy')]);
const writeMember = async (m: any) => applyWrite('members', await deltaToWhole('members', [m], []));
const denied = (fn: () => Promise<unknown>, label: string) => assert.rejects(fn, (e: unknown) => e instanceof GuardError, label);
await writeMember(member('allowed', 'church', 'church_bus'));
await denied(() => writeMember(member('cross', 'light', 'church_bus')), 'affectation interbranche refusée');
await denied(() => writeMember(member('unknown', 'church', 'missing')), 'bus inexistant refusé');
await denied(() => writeMember(member('unresolved', 'church', 'legacy')), 'branche non résolue refusée');
await denied(() => writeMember(member('allowed', 'light', 'church_bus')), 'transfert de branche sans changer le bus refusé');
await setCollection('members', [...await getCollection('members'), member('legacy_wrong', 'light', 'church_bus')]);
await denied(() => writeMember({ ...member('legacy_wrong', 'light', 'church_bus'), busRole: 'capitaine' }), 'nomination sur un rattachement incohérent refusée');
await applyWrite('members', await deltaToWhole('members', [], ['legacy_wrong']));
await denied(async () => applyWrite('bus_lines', await deltaToWhole('bus_lines', [bus('new')], [])), 'création sans branche refusée');
await denied(async () => applyWrite('bus_lines', await deltaToWhole('bus_lines', [bus('church_bus', 'light')], [])), 'changement incompatible avec les membres refusé');
await applyWrite('bus_lines', await deltaToWhole('bus_lines', [bus('legacy', 'light')], []));
await writeMember(member('allowed', 'light', 'light_bus'));
assert.equal((await getCollection('members')).filter(m => !m.deletedAt).length, 1, 'les refus ne créent aucun profil');

await setCollection('departments', [{ id: 'bb', specialFunction: 'bloom_bus', ministryId: 'retention' }]);
await setCollection('ministries', []);
const op = { ...member('operator', 'church'), departments: { bb: 'responsable' }, deptBranches: { bb: 'light' } };
const ctx = { member: op, roles: ['Responsable', 'Membre'] };
const lines = await getCollection('bus_lines');
assert.equal((await filterReadable('bus_lines', ctx, lines)).length, 3, 'découverte Church et autorité Light cumulées');
assert.deepEqual((await filterReadable('bus_lines', { member: member('plain', 'church'), roles: ['Membre'] }, lines)).map(b => b.id), ['church_bus']);
await assertCanWrite('bus_lines', ctx, await deltaToWhole('bus_lines', [bus('new_light', 'light')], []));
await denied(async () => assertCanWrite('bus_lines', ctx, await deltaToWhole('bus_lines', [bus('new_church', 'church')], [])), 'responsable Light ne crée pas dans Church');
console.log('busBranch.check OK');
